### ISSUE TITLE
Microsoft 365 products

### ISSUE THREAD

**Issue by mmatloch** [dheereshagrwal/colored-icons#21]
Hey there,

Could you please add the Microsoft 365 product icons to the repository? 
These icons are available at the bottom of this page: https://developer.microsoft.com/en-us/fluentui#/styles/web/m365-product-icons#product-icon-library

Specifically, it would be great to have icons for:

* Outlook
* OneDrive
* Word
* Excel
* Teams

Thanks a lot!

**Comment by dheereshagrwal** [comment]
yeah picking this up and I am working on revamping the search too.

**Comment by dheereshagrwal** [comment]
yeah picking this up and I am working on revamping the search too.

**Comment by dheereshagrwal** [comment]
done plz use latest release 1.7.6
