### ISSUE TITLE
More social media and portfolio platforms

### ISSUE THREAD

**Issue by aulerius** [dheereshagrwal/colored-icons#7]
Hi! Thank you for this!

I'd love to use it for social media and portfolio links, but some obvious ones are missing, especially related to Arts or Music.
I personally would like Vimeo and Behance.

But some more obvious ones for you to consider if you want, are Reddit, TikTok, SnapChat, Pinterest, Soundcloud, Mixcloud, Bandcamp, Twitch, DeviantArt, Artstation, Dribble.

**Comment by vellvisher** [comment]
Perhaps controversial, add X too? Thanks, this repo is great!

**Comment by dheereshagrwal** [comment]
I will add X as well. When I started this project, at that time, there was no X😂

**Comment by vellvisher** [comment]
Thanks :)

**Comment by dheereshagrwal** [comment]
I have added X also
